apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo1
  template:
    metadata:
      labels:
        app: gitops-demo1
    spec:
      containers:
        - name: gitops-demo1
          image: acr798b329f69ffe2be.azurecr.io/gitops-demo1:3e5f36092ce04d8cd2c66077a949ac6bee6f54c4
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo2
  template:
    metadata:
      labels:
        app: gitops-demo2
    spec:
      containers:
        - name: gitops-demo2
          image: acr798b329f69ffe2be.azurecr.io/gitops-demo2:3e5f36092ce04d8cd2c66077a949ac6bee6f54c4
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo3
  template:
    metadata:
      labels:
        app: gitops-demo3
    spec:
      containers:
        - name: gitops-demo3
          image: acr798b329f69ffe2be.azurecr.io/gitops-demo3:3e5f36092ce04d8cd2c66077a949ac6bee6f54c4
          ports:
            - containerPort: 5000
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo1
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: gitops-demo1
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo2
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: gitops-demo2
---          
apiVersion: v1
kind: Service
metadata:
  name: gitops-demo3
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: gitops-demo3
---        
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-ingress
spec:
  ingressClassName: external-nginx
  rules:
  - http:
      paths:
      - path: /demo1
        pathType: Prefix
        backend:
          service:
            name: gitops-demo1
            port:
              number: 5000
      - path: /demo2
        pathType: Prefix
        backend:
          service:
            name: gitops-demo2
            port:
              number: 5000
      - path: /demo3
        pathType: Prefix
        backend:
          service:
            name: gitops-demo3
            port:
              number: 5000